- name: "Installation servers srv-web1, web2"
  hosts: webservers
  become: true
  vars_files:
    - ./vars/secret-variables.yaml
  pre_tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: true

  tasks:

    - name: Create Frontend Network
      community.docker.docker_network:
        name: frontend
        state: present

    - name: Create Backend Network
      community.docker.docker_network:
        name: backend
        state: present

    - name: Create Persistent MySQL Volume
      community.docker.docker_volume:
        name: mysql_data

    - name: Create Directory
      ansible.builtin.file:
        path: /home/admin/html
        state: directory
        owner: admin
        group: admin
        mode: 0755

    - name: Create Directory
      ansible.builtin.file:
        path: /home/admin/HttpdConf
        state: directory
        owner: admin
        group: admin
        mode: 0755

    - name: Uploade index.php
      copy:
        src: ./html/index.php
        dest: /home/admin/html/index.php
        mode: 0755

    - name: Upload httpd.conf
      copy:
        src: ./HttpdConf/httpd.conf
        dest: /home/admin/HttpdConf/httpd.conf

    - name: Create PHP-FPM Container
      community.docker.docker_container:
        name: php-fpm-container
        image: php:fpm-alpine
        ports:
          - "9000:9000"
        networks:
          - backend

    - name: Create Apache Container
      community.docker.docker_container:
        name: apache2-container
        image: httpd:alpine
        ports:
          - "80:80"
        volumes:
          - /home/admin/html/index.php:/usr/local/apache2/htdocs/index.php
          - /home/admin/HttpdConf/:/usr/local/apache2/conf/
        networks:
          - frontend
          - backend
        state: present

    - name: Create MySQL Container
      community.docker.docker_container:
        name: mysql-container
        image: mysql:latest
        ports:
          - "3306:3306"
        volumes:
          - mysql_data:/var/lib/mysql
        environment:
          MYSQL_ROOT_PASSWORD: rootpassword
        networks:
          - backend
        state: present

